# Konfigurasi aplikasi RAG Chatbot PDF
qdrant:
  host: localhost
  port: 6333
  collection: laws
postgresql:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  db: ragdb
embedding:
  model: sentence-transformers/all-MiniLM-L6-v2
llm:
  model: gpt-3.5-turbo
retriever:
  top_k: 4
  mmr_lambda: 0.3
  threshold: 0.28
chunk:
  size: 1000
  overlap: 120
